# Étape 1 : Construction de l'application
FROM maven:3.9.5-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Étape 2 : Image finale
FROM openjdk:17-slim
WORKDIR /app
COPY --from=build /app/target/*.jar /app/pipeline-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/app/pipeline-0.0.1-SNAPSHOT.jar"]
