# Utiliser une image de base avec Java 17
FROM eclipse-temurin:17-jdk

# Répertoire d'application dans le conteneur
WORKDIR /app

# Copier le fichier JAR dans le conteneur
COPY target/*.jar /app/pipeline-0.0.1-SNAPSHOT.jar

# Commande pour exécuter l'application Spring Boot
ENTRYPOINT ["java", "-jar", "/app/pipeline-0.0.1-SNAPSHOT.jar"]
