FROM maven:3.6.3-amazoncorretto
WORKDIR /app
COPY . .
RUN mvn clean package
FROM openjdk:24-slim-bullseye
WORKDIR /app
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} /app/pipeline-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/app/pipeline-0.0.1-SNAPSHOT.jar"]